[package]
name = "aivpn-admin-web"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "aivpn-admin-web"
path = "src/main.rs"

[dependencies]
base64 = "0.22"
clap = { version = "4.4", features = ["derive", "env"] }
qrcode = { version = "0.14", default-features = false, features = ["svg"] }
rand.workspace = true
serde_json.workspace = true
